import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
        Random generator = new Random(seed);  
		int two = 0;
        int three = 0;
        int four = 0;
        double amount = 0.0; 
        String child = "";
            
        for (int i = 1 ; i <= T ; i++) {
            while (child.indexOf("g") == (-1) || child.indexOf("b") == (-1)) {
                if (generator.nextDouble() < 0.5) { 
                    child += "g ";
                } else {
                    child += "b ";
                    }
                }    
                if (child.length() / 2 == 2) {
                    two += 1;
                } 
                if (child.length() / 2 == 3){
                    three += 1;
                }
                if (child.length() / 2 > 3) {
                    four +=1;
                }
                amount += child.length() / 2;
                child = "";
            }
            double average = amount / T;
            System.out.println("Average: " + average + " children to get at least one of each gender.");
            System.out.println("Number of families with 2 children: " + two);
            System.out.println("Number of families with 3 children: " + three);
            System.out.println("Number of families with 4 or more children: " + four);
        if (two < three) {
            if (three >= four) {
             System.out.println("The most common number of children is .");
            } else { System.out.println("The most common number of children is 4 or more.");
            }
        } else {
            if (two >= four) {
             System.out.println("The most common number of children is 2.");   
            } else { 
            System.out.println("The most common number of children is 4 or more.");
        }
        }	    
	}
}
